
#define PlatformConsoleOut(Format, ...) Platform.ConsoleOut(Format, __VA_ARGS__)
#define PlatformConsoleOut_(Format, ArgsList) Platform.ConsoleOut_(Format, ArgsList)
#define PlatformAllocateMemory(Size, Flags) Platform.AllocateMemory(Size, Flags)
#define PlatformDeallocateMemory(Block) Platform.DeallocateMemory(Block)
#define PlatformFileExists(Path) Platform.FileExists(Path)
#define PlatformReadEntireFile(Arena, FilePath) Platform.ReadEntireFile(Arena, FilePath)
#define PlatformWriteTextToFile(Text, FilePath) Platform.WriteTextToFile(Text, FilePath)
#define PlatformOpenFile(FilePath, Flags) Platform.OpenFile(FilePath, Flags)
#define PlatformWriteFile(File, Text) Platform.WriteFile(File, Text)
#define PlatformCloseFile(File) Platform.CloseFile(File)
#define PlatformGetOSTimerFrequency() Platform.GetOSTimerFrequency()
#define PlatformReadOSTimer() Platform.ReadOSTimer()
#define PlatformReadOSPageFaultCount() Platform.ReadOSPageFaultCount()
#define PlatformReadCPUTimer() __rdtsc()
